[package]
name = "obscura-egui-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.32" 
rfd = "0.14"
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"  
anyhow = "1.0.100"